In [37]:
import re
import numpy as np
import pandas as pd
from tqdm import tqdm
import country_converter as coco

In [89]:
df = pd.read_parquet("../data/final_clean.csv")

In [90]:
df

,conflict_id,year,side_a,side_a_2nd,side_b,side_b_2nd,iso3_a,iso3_a_2nd,iso3_b,iso3_b_2nd,...,version_prio,prio_merge,bd_best,bd_low,bd_high,deaths_best,deaths_low,deaths_high,deaths_estimate,deaths_source
0,200,1946,Government of Bolivia,None,Popular Revolutionary Movement,None,BOL,None,None,None,...,2009-4,both,NaN,NaN,NaN,1000.0,1000.0,9999.0,1000.0,PRIO_v3.1 (point)
1,200,1946,Government of Bolivia,None,Popular Revolutionary Movement,None,BOL,None,None,None,...,2009-4,both,NaN,NaN,NaN,1000.0,1000.0,9999.0,1000.0,PRIO_v3.1 (point)
2,200,1946,Government of Bolivia,None,Popular Revolutionary Movement,None,BOL,None,None,None,...,2009-4,both,NaN,NaN,NaN,1000.0,1000.0,9999.0,1000.0,PRIO_v3.1 (point)
3,200,1946,Government of Bolivia,None,Popular Revolutionary Movement,None,BOL,None,None,None,...,2009-4,both,NaN,NaN,NaN,1000.0,1000.0,9999.0,1000.0,PRIO_v3.1 (point)
4,200,1946,Government of Bolivia,None,Popular Revolutionary Movement,None,BOL,None,None,None,...,2009-4,both,NaN,NaN,NaN,1000.0,1000.0,9999.0,1000.0,PRIO_v3.1 (point)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438420,16470,2025,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,YEM,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1
438421,16470,2025,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,YEM,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1
438422,16470,2025,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,YEM,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1
438423,16470,2025,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,YEM,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1
438424,16470,2025,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,YEM,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1

In [92]:
df[['country_code', 'year', 'conflict_id', 'has_conflict_mention','side_a', 'side_a_2nd', 'side_b', 'side_b_2nd',
       'iso3_a', 'iso3_a_2nd', 'iso3_b', 'iso3_b_2nd', 'iso3_loc',
       'intensity_level', 'cumulative_intensity', 'type_of_conflict',
       'main_actor', 'secondary_actor',
       'conflict_host', 'side_a_ideals_diff', 'side_b_ideals_diff',
       'side_a_dist', 'side_b_dist', 'location', 'incompatibility',
       'territory_name', 'start_date', 'start_prec', 'start_date2',
       'start_prec2', 'ep_end', 'ep_end_date', 'ep_end_prec', 'region',
       'version', 'bdeadlow', 'bdeadhig', 'bdeadbes', 'annualdata', 'source',
       'bdversion', 'location_prio', 'incomp', 'terr', 'int', 'cumint', 'type',
       'startdate', 'startprec', 'startdate2', 'startprec2', 'epend',
       'ependdate', 'ependprec', 'region_prio', 'version_prio', 'prio_merge',
       'bd_best', 'bd_low', 'bd_high', 'deaths_best', 'deaths_low',
       'deaths_high', 'deaths_estimate', 'deaths_source']].sort_values(['country_code', 'year', 'conflict_id'])

,country_code,year,conflict_id,has_conflict_mention,side_a,side_a_2nd,side_b,side_b_2nd,iso3_a,iso3_a_2nd,...,version_prio,prio_merge,bd_best,bd_low,bd_high,deaths_best,deaths_low,deaths_high,deaths_estimate,deaths_source
74,AFG,1952,200,False,Government of Bolivia,None,MNR,None,BOL,None,...,2009-4,both,NaN,NaN,NaN,NaN,450.0,3000.0,1725.0,PRIO_v3.1 (range)
474,AFG,1952,201,False,Government of France,None,Khmer Issarak,None,FRA,None,...,2009-4,both,NaN,NaN,NaN,NaN,25.0,999.0,512.0,PRIO_v3.1 (range)
4088,AFG,1952,208,False,Government of France,None,Lao Issara,None,FRA,None,...,2009-4,both,NaN,NaN,NaN,NaN,25.0,999.0,512.0,PRIO_v3.1 (range)
4422,AFG,1952,209,False,Government of Philippines,None,Huk,None,PHL,None,...,2009-4,both,NaN,NaN,NaN,1077.0,1000.0,2154.0,1077.0,PRIO_v3.1 (point)
14540,AFG,1952,216,False,Government of France,None,Viet minh,None,FRA,None,...,2009-4,both,NaN,NaN,NaN,41947.0,23566.0,66667.0,41947.0,PRIO_v3.1 (point)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435735,ZWE,2025,15256,False,Government of Benin,None,JNIM,None,BEN,None,...,None,left_only,149.0,140.0,193.0,149.0,140.0,193.0,149.0,UCDP_v26.1
436887,ZWE,2025,16038,False,Government of Mali,Government of Russia (Soviet Union),FLA,None,MLI,RUS,...,None,left_only,82.0,81.0,144.0,82.0,81.0,144.0,82.0,UCDP_v26.1
437461,ZWE,2025,16069,False,Government of Ethiopia,None,Fano,None,ETH,None,...,None,left_only,3835.0,2275.0,12282.0,3835.0,2275.0,12282.0,3835.0,UCDP_v26.1
437843,ZWE,2025,16099,False,"Government of United Kingdom, Government of Un...","Government of Australia, Government of Bahrain...",Government of Yemen (North Yemen),None,"GBR, USA","CAN, NLD, NOR, BHR, LKA, SGP, AUS, NZL",...,None,left_only,781.0,337.0,1044.0,781.0,337.0,1044.0,781.0,UCDP_v26.1
438424,ZWE,2025,16470,False,Government of Israel,None,Government of Yemen (North Yemen),None,ISR,None,...,None,left_only,164.0,94.0,197.0,164.0,94.0,197.0,164.0,UCDP_v26.1

In [96]:
df[['country_code', 'year', 'conflict_id', 'iso3_loc', 'has_conflict_mention', 'intensity_level', 'side_a_ideals_diff',
       'side_a_dist', 'deaths_best', 'deaths_low',
       'deaths_high']].sort_values(['year', 'country_code', 'conflict_id']).head(55)

,country_code,year,conflict_id,iso3_loc,has_conflict_mention,intensity_level,side_a_ideals_diff,side_a_dist,deaths_best,deaths_low,deaths_high
0,ARG,1946,200,BOL,True,2,0.295676,1865.8390,1000.0,1000.0,9999.0
227,ARG,1946,201,KHM,False,1,0.425127,10932.3400,NaN,25.0,999.0
561,ARG,1946,202,CHN,False,2,NaN,19110.1300,200000.0,16666.0,333333.0
713,ARG,1946,203,GRC,False,2,1.055082,11772.0400,38500.0,6000.0,40000.0
865,ARG,1946,204,IDN,False,1,1.034770,11434.1000,NaN,655.0,5000.0
1017,ARG,1946,205,IRN,False,1,0.532516,13881.9600,25.0,0.0,1000.0
3763,ARG,1946,206,IRN,False,1,0.532516,13881.9600,20.0,20.0,1000.0
3802,ARG,1946,207,ISR,False,1,1.457434,11136.9600,92.0,92.0,373.0
3841,ARG,1946,208,LAO,False,1,0.425127,10932.3400,NaN,25.0,999.0
4175,ARG,1946,209,PHL,False,2,0.322147,17783.1100,1077.0,1000.0,2154.0
13746,ARG,1946,210,RUS,False,1,4.006409,14195.3300,410.0,25.0,410.0
13863,ARG,1946,211,RUS,False,1,4.006409,14195.3300,557.0,25.0,557.0
13902,ARG,1946,212,RUS,False,2,4.006409,14195.3300,3971.0,1000.0,3971.0
14019,ARG,1946,213,RUS,False,2,4.006409,14195.3300,7942.0,1000.0,7942.0
14215,ARG,1946,214,"FRA, THA",False,1,0.425127,10932.3400,NaN,102.0,275.0
14254,ARG,1946,215,"GBR, ALB",False,1,NaN,11662.5600,NaN,38.0,44.0
14293,ARG,1946,216,VNM,False,2,0.425127,10932.3400,41947.0,23565.0,66666.0
1,AUS,1946,200,BOL,False,2,0.274260,13370.4600,1000.0,1000.0,9999.0
228,AUS,1946,201,KHM,False,1,0.403710,16513.0200,NaN,25.0,999.0
562,AUS,1946,202,CHN,False,2,NaN,8345.1100,200000.0,16666.0,333333.0
714,AUS,1946,203,GRC,False,2,1.076499,14845.6000,38500.0,6000.0,40000.0
866,AUS,1946,204,IDN,False,1,1.056186,16227.4500,NaN,655.0,5000.0
1018,AUS,1946,205,IRN,False,1,0.511100,12373.1800,25.0,0.0,1000.0
3764,AUS,1946,206,IRN,False,1,0.511100,12373.1800,20.0,20.0,1000.0
3803,AUS,1946,207,ISR,False,1,1.478851,16602.2700,92.0,92.0,373.0
3842,AUS,1946,208,LAO,False,1,0.403710,16513.0200,NaN,25.0,999.0
4176,AUS,1946,209,PHL,False,2,0.300730,5896.9230,1077.0,1000.0,2154.0
13747,AUS,1946,210,RUS,False,1,3.984993,13424.9000,410.0,25.0,410.0
13864,AUS,1946,211,RUS,False,1,3.984993,13424.9000,557.0,25.0,557.0
13903,AUS,1946,212,RUS,False,2,3.984993,13424.9000,3971.0,1000.0,3971.0
14020,AUS,1946,213,RUS,False,2,3.984993,13424.9000,7942.0,1000.0,7942.0
14216,AUS,1946,214,"FRA, THA",False,1,0.403710,16513.0200,NaN,102.0,275.0
14255,AUS,1946,215,"GBR, ALB",False,1,NaN,15208.5000,NaN,38.0,44.0
14294,AUS,1946,216,VNM,False,2,0.403710,16513.0200,41947.0,23565.0,66666.0
2,BEL,1946,200,BOL,False,2,0.709133,10200.1100,1000.0,1000.0,9999.0
229,BEL,1946,201,KHM,False,1,0.838584,526.3351,NaN,25.0,999.0
563,BEL,1946,202,CHN,False,2,NaN,8370.6100,200000.0,16666.0,333333.0
715,BEL,1946,203,GRC,False,2,0.641625,2050.8430,38500.0,6000.0,40000.0
867,BEL,1946,204,IDN,False,1,0.621313,160.9283,NaN,655.0,5000.0
1019,BEL,1946,205,IRN,False,1,0.945973,4177.1730,25.0,0.0,1000.0
3765,BEL,1946,206,IRN,False,1,0.945973,4177.1730,20.0,20.0,1000.0
3804,BEL,1946,207,ISR,False,1,1.043977,448.2817,92.0,92.0,373.0
3843,BEL,1946,208,LAO,False,1,0.838584,526.3351,NaN,25.0,999.0
4177,BEL,1946,209,PHL,False,2,0.735604,10677.6000,1077.0,1000.0,2154.0
13748,BEL,1946,210,RUS,False,1,4.419866,3010.8040,410.0,25.0,410.0
13865,BEL,1946,211,RUS,False,1,4.419866,3010.8040,557.0,25.0,557.0
13904,BEL,1946,212,RUS,False,2,4.419866,3010.8040,3971.0,1000.0,3971.0
14021,BEL,1946,213,RUS,False,2,4.419866,3010.8040,7942.0,1000.0,7942.0
14217,BEL,1946,214,"FRA, THA",False,1,0.838584,526.3351,NaN,102.0,275.0
14256,BEL,1946,215,"GBR, ALB",False,1,NaN,1609.0680,NaN,38.0,44.0
14295,BEL,1946,216,VNM,False,2,0.838584,526.3351,41947.0,23565.0,66666.0
3,BLR,1946,200,BOL,False,2,3.813417,11820.5300,1000.0,1000.0,9999.0
230,BLR,1946,201,KHM,False,1,3.683966,1948.5690,NaN,25.0,999.0
564,BLR,1946,202,CHN,True,2,NaN,6851.6840,200000.0,16666.0,333333.0
716,BLR,1946,203,GRC,True,2,5.164175,1737.3710,38500.0,6000.0,40000.0

In [104]:
df[['country_code', 'year', 'conflict_id', 'iso3_loc', 'has_conflict_mention', 'intensity_level', 'side_a_ideals_diff',
       'side_a_dist', 'deaths_best', 'deaths_low',
       'deaths_high']].groupby(['country_code', 'year']).agg(sum).head(55)

C:\Users\SemKj\AppData\Local\Temp\ipykernel_11704\3872609430.py:3: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  'deaths_high']].groupby(['country_code', 'year']).agg(sum).head(55)

                   conflict_id  \
country_code year
AFG          1952         3102
             1957         4122
             1958         4382
             1959         3897
             1960         3804
             1961         5341
             1962         5076
             1963         5061
             1964         6560
             1965         7116
             1966         7433
             1968         6907
             1969        18848
             1971         7941
             1972         7160
             1973        18316
             1974         7913
             1975         8759
             1976         9336
             1977        10766
             1978        11602
             1979        12442
             1980        12386
             1981        12632
             1982        13059
             1983        13037
             1984        12500
             1985        11462
             1986        13477
             1987        14308
             1988        11870
             1989        12641
             1990        15512
             1991        39437
             1992        16808
             1993        14897
             1994        16693
             1995        25005
             1996        13342
             1997        13018
             1998        13673
             1999        13673
             2000        24263
             2001        36963
             2002        10931
             2003        11048
             2004        11350
             2005        32799
             2006        32913
             2007        22911
             2008        24164
             2009        23417
             2010        10388
             2011        45138
             2012        67667

                                                            iso3_loc  \
country_code year
AFG          1952  BOLKHMLAOPHLVNMMMRMMRMMRMMRMYSISRPRK, KORGBR, ...
             1957  MMRMMRMMRMMRMYSISRCUBDZACYPVNMINDMMRCMRHND, NI...
             1958  MMRMMRMMRMMRCHN, TWNISRCUBIDNDZACYPVNMINDCMRMR...
             1959   MMRMMRMMRMMRISRCHNIDNDZACYPVNMINDCMRIRQMYSLAOMMR
             1960      MMRMMRMMRMMRISRIDNDZAVNMMYSLAOMMRCODETHNPLCMR
             1961  MMRMMRMMRMMRMMRISRCUBIDNDZAVNMINDLAOAGOMMRCODC...
             1962  MMRMMRMMRYEMMMRISRDZAVNMINDAGOMMRCODCODNPLFRAI...
             1963  MMRMMRMMRYEMMMRGTMISRARGVNMINDIRQLAOAGOMMRIRQM...
             1964  IND, PAKMMRMMRMMRYEMMMRISRVNMINDLAOAGOMMRSOM, ...
             1965  IND, PAKMMRMMRMMRYEMMMRGTMISRINDLAOAGOMMRIRQET...
             1966  IRNMMRMMRMMRYEMMMRGTMISRINDLAOAGOMMRIRQETHGNBM...
             1968  IRNMMRMMRMMRYEMMMRGTMISRINDLAOAGOMMRIRQETHGNBS...
             1969  PHLMMRMMRMMRINDYEMMMRGTMISRLAOAGOMMRIRQETHGNBS...
             1971  PHLIND, PAKMMRMMRMMRINDMMRGTMISRLAOAGOETHGNBSD...
             1972  PHLMMRMMRMMRMMRGTMISRLAOAGOMMRETHGNBSDNMOZTCDC...
             1973  PHLMMRMMRMMRMMRGTMISRLAOAGOMMRIRQETHGNBMOZCOLV...
             1974  PHLMMRMMRMMRMMRGTMISRTHAARGMYSAGOIRQETHMOZCOLV...
             1975  PHLMMRMMRMMRMMRGTMISRTHAARGLBNMYSIRQETHCOLVNM,...
             1976  PHLMMRMMRMMRMMRGTMISRTHAARGLBNMMRETHIRQETHTCDC...
             1977  PHLMMRMMRMMRMMRGTMISRTHAARGMMRETHSOM, ETHIRQET...
             1978  PHLMMRMMRMMRMMRGTMISRTHAMMRETHSOM, ETHIRQETHCO...
             1979  IRNPHLMMRMMRYEMMMRGTMISRTHAMMRETHIRQETHTCDCOLZ...
             1980  IRNPHLMMRMMRYEMMMRGTMISRTHAMMRETHSOM, ETHIRQET...
             1981  IRNPHLMMRMMRYEMMMRGTMISRTHAMYSMMRETHIRQETHTCDC...
             1982  IRNPHLMMRMMRYEMMMRGTMISRTHAIRQLBNMMRETHIRQETHV...
             1983  IRNPHLMMRMMRMMRGTMISRIRQLBNMMRETHIRQETHTCDCOLP...
             1984  IRNPHLIND, PAKMMRMMRMMRGTMISRIRQLBNMMRETHIRQET...
             1985  IRNPHLMMRMMRMMRGTMISRLBNMMRETHIRQETHCOLPERZAFK...
             1986  IRNPHLMMRMMRMMRGTMISRLBNMMRETHIRQETHTCDCOLPERZ...
             1987  IRNPHLIND, PAKMMRMMRMMRGTMISRMMRIRQMMRETHIRQET...
             1988  IRNPHLMMRMMRMMRGTMISRMMRETHIRQETHCOLPERZAFKHMP...
             1989  PHLIND, PAKPRYMMRMMRGTMISRLBNLAOETHIRQETHTCDCO...
             1990  IRNPHLIND, PAKMMRMMRMMRMMRGTMISRLBNLAOETHIRQET...
             1991  PHLIND, PAKMMRMMRMMRINDMMRGTMISRIRQETHIRQETHBD...
             1992  PHLIND, PAKMMRMMRINDMMRGTMISRINDMMRIRQIRQVENBD...
             1993  IRNPHLINDGTMISRINDIRQMMRTCDCOLPERKHMPHLSDNAGOE...
             1994  PHLIND, PAKMMRMMRMMRINDGTMISRINDIRQMMRBDITCDCO...
             1995  PHLMMRGTMISRINDIRQMMRIRQBDICOLPERKHMPHLSDNUGAA...
             1996  IRNIND, PAKMMRINDISRINDMMRIRQMMRNPLIRQCODBDICO...
             1997  PHLIND, PAKMMRINDINDMMRNPLCODBDITCDCOLPERKHMPH...
             1998  IND, PAKMMRINDMMRNPLCODBDITCDCOLPERKHMPHLSDNUG...
             1999  PHLIND, PAKINDMMRNPLCODBDITCDCOLPERPHLSDNUGAER...
             2000  PHLIND, PAKMMRINDISRINDMMRNPLCODBDITCDCOLGINPH...
             2001  PHLIND, PAKMMRINDISRMMRNPLCODBDITCDCOLGINPHLSD...
             2002  PHLIND, PAKMMRINDISRMMRNPLBDITCDCOLPHLSDNUGAAG...
             2003  PHLIND, PAKMMRINDISRNPLBDITCDCOLPHLSDNUGAERIET...
             2004  PHLMMRINDISRIRQNPLBDICOLPHLSDNUGAPAKETHAFGINDI...
             2005  PHLMMRINDISRMMRIRQMMRNPLCODBDITCDCOLPHLSDNUGAE...
             2006  PHLMMRINDISRIRQMMRNPLCODBDITCDCOLPHLSDNUGAPAKE...
             2007  PHLMMRINDISRIRQMMRCODTCDCOLPERPHLSDNUGAPAKETHA...
             2008  PHLMMRINDYEMISRIRQMMRCODBDITCDCOLPERPHLSDNUGAP...
             2009  PHLMMRINDYEMISRIRQMMRTCDCOLPERNGAPHLSDNUGAPAKE...
             2010  PHLMMRINDYEMISRIRQMMRTCDCOLPERPHLSDNUGAETHAFGS...
             2011  PHLMMRINDYEMMMRISRIRQMMRCODCOLTHA, KHMNGASYRPH...
             2012  PHLINDYEMMMRISRIRQCODCOLNGASYRPHLSDNPAKETHAFGS...

                   has_conflict_mention  intensity_level  side_a_ideals_diff  \
country_code year
AFG          1952                     0               19           21.438181
             1957                     0               19           24.488866
             1958                     2               24           25.751242
             1959                     2               21           21.892470
             1960                     1               19           24.321379
             1961                     0               30           21.788085
             1962                     2               27           16.020414
             1963                     0               27           12.256591
             1964                     0               32            0.000000
             1965                     2               35           27.412918
             1966                     6               35           32.910108
             1968                     1               33           28.353118
             1969                     2               38           34.446400
             1971                     7               39           30.773543
             1972                     1               32           23.616336
             1973                     5               33           23.744662
             1974                     6               34           17.515428
             1975                     6               37           11.031314
             1976                     4               40           11.583738
             1977                     4               44           13.218137
             1978                    10               52           42.774768
             1979                    10               51           39.658665
             1980                    10               50           58.775520
             1981                     9               55           54.462683
             1982                    14               59           57.497978
             1983                    16               57           46.178453
             1984                    10               57           53.805393
             1985                    10               51           50.963548
             1986                    11               56           43.206340
             1987                    10               62           39.830907
             1988                    13               55           25.232747
             1989                     8               51           28.263736
             1990                    11               63           26.994074
             1991                     6               66           28.816295
             1992                     8               65           24.990361
             1993                     3               53           32.387421
             1994                    12               60           37.591003
             1995                     7               50           31.086414
             1996                     1               51           30.461029
             1997                     3               48           18.825833
             1998                     1               52           16.162413
             1999                     2               52           18.067344
             2000                     2               52           18.633995
             2001                     2               47           20.640233
             2002                     8               40           16.667603
             2003                     3               39           19.937847
             2004                     3               40           19.731734
             2005                     1               38           20.723358
             2006                     3               39           18.682285
             2007                     9               39           15.929461
             2008                    11               44           17.547882
             2009                     3               44           16.820191
             2010                     8               35           15.352887
             2011                     8               44           18.604654
             2012                     5               39           16.809645

                   side_a_dist  deaths_best  deaths_low  deaths_high
country_code year
AFG          1952   73932.8160     147221.0     91963.0     236832.0
             1957   88548.7380      31331.0     20472.0      88928.0
             1958   84688.4490      45157.0     22769.0     103899.0
             1959   64504.8240      50958.0     24892.0     203098.0
             1960   57481.5210      33396.0     50620.0     284313.0
             1961   86097.0830      43842.0     56575.0     321743.0
             1962   80420.1440      52012.0     24475.0     201768.0
             1963  101665.6100      63100.0     50362.0     226282.0
             1964  111994.3360      56286.0     46296.0     263982.0
             1965  150869.6090      90935.0     69004.0     357463.0
             1966  143962.9180      88243.0     71075.0     325866.0
             1968  134304.8230     224942.0    172772.0     713401.0
             1969  157899.5500     188677.0    143211.0     589961.0
             1971  149536.0252     200623.0    207357.0     826935.0
             1972  160362.3610     289861.0    228035.0     878233.0
             1973  148095.4750     214668.0    171309.0     618296.0
             1974  150919.8782     237427.0    202658.0     719301.0
             1975  165800.4762     117095.0     84729.0     240474.0
             1976  177830.1572      94664.0     25774.0     166983.0
             1977  204557.4332      33406.0     25944.0      96763.0
             1978  204879.2203      87715.0     47477.0     173508.0
             1979  207066.1676     146019.0     62808.0     253631.0
             1980  203050.4653     113625.0     72283.0     247888.0
             1981  219515.5933     181771.0    100040.0     383186.0
             1982  253897.7013     217647.0     99527.0     457330.0
             1983  243790.4973     214784.0    100999.0     442352.0
             1984  222081.6763     237032.0     88222.0     437832.0
             1985  212868.6993     216678.0     83678.0     396348.0
             1986  236191.6933     213493.0     93398.0     407295.0
             1987  255544.0643     181641.0     70767.0     342771.0
             1988  210451.0243     141117.0     64948.0     502789.0
             1989  262494.7493      55667.0     51133.0      85681.0
             1990  260322.9565      80297.0     77085.0      97820.0
             1991  267397.4283      70355.0     68111.0      91419.0
             1992  248369.4345      53410.0     49968.0      78170.0
             1993  201436.2685      44954.0     43928.0      67762.0
             1994  241506.4427      38523.0     37239.0      58171.0
             1995  210401.6067      36755.0     35696.0      52212.0
             1996  176019.1207      28903.0     28460.0      35089.0
             1997  174074.1965      40389.0     37191.0      62033.0
             1998  191757.9855      40238.0     38147.0      52246.0
             1999  177256.1153      81444.0     80033.0     104048.0
             2000  164594.5395      78674.0     76413.0      91469.0
             2001  169287.3356      23623.0     21247.0      38799.0
             2002  162276.2123      21157.0     19106.0      29330.0
             2003  149548.0593      23265.0     22831.0      33593.0
             2004  150590.8825      19716.0     19210.0      26777.0
             2005  129132.4903      12437.0     12026.0      15579.0
             2006  128825.0705      20287.0     19063.0      28904.0
             2007  151117.0047      19381.0     18392.0      25488.0
             2008  160164.5007      28867.0     28014.0      37231.0
             2009  173051.2387      36006.0     32655.0      44916.0
             2010  142350.9497      21652.0     20599.0      28584.0
             2011  153385.5679      25636.0     24476.0      34219.0
             2012  131210.1147      74155.0     71759.0      85523.0